spring:
    profiles:
        active: 
        - dev 
-----       
spring:
    profiles: dev #开发环境
    appllcation: 
        name: microservicecloud-config-atguigu-dev 
-----
spring: 
    profiles: test #测试环境 
    application:
        name: microservicecloud-config-atguigu-test